library:
  source-dirs: src
tests:
  infix-lisp-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - infix-lisp
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- string-qq
- repline
- text
- containers
- base >= 4.7 && < 5
- megaparsec >= 8.0.0 && < 8.1
name: infix-lisp
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/infix-lisp
license: BSD3
executables:
  infix-lisp-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - infix-lisp
description: Please see the README on GitHub at <https://github.com/githubuser/infix-lisp#readme>
